logsBucket: 'eth-gas-watch_cloudbuild'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--target=dependencies'
  - '-t'
  - 'gcr.io/eth-gas-watch/send-tweet:dependencies'
  - '.'
  timeout: '120s'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/eth-gas-watch/send-tweet:latest'
  - '--cache-from=gcr.io/eth-gas-watch/send-tweet:dependencies'
  - '.'
  timeout: '120s'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/eth-gas-watch/send-tweet:latest'
  timeout: '120s'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'send-tweet'
  - '--region'
  - 'eu-west1'
  - '--runtime'
  - 'python310'
  - '--entry-point'
  - 'send_tweet'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--log-http'
  - 'gs://eth-gas-watch_cloudbuild/logs'
  - '--source'
  - 'gcr.io/eth-gas-watch/send-tweet:latest'
  timeout: '120s'
