logsBucket: 'eth-gas-watch_cloudbuild'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/eth-gas-watch/send-tweet', '.' ]
  timeout: '1000s'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/eth-gas-watch/send-tweet']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'send-tweet'
  - '--region'
  - 'eu-west1'
  - '--runtime'
  - 'python310'
  - '--entry-point'
  - 'send_tweet'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--log-http'
  - 'gs://eth-gas-watch_cloudbuild/logs'
  timeout: '1000s'
